// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.xproce.lab;

/**
 * Protobuf type {@code org.xproce.lab.VideoStream}
 */
public  final class VideoStream extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.xproce.lab.VideoStream)
    VideoStreamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VideoStream.newBuilder() to construct.
  private VideoStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VideoStream() {
    videos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VideoStream();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VideoStream(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              videos_ = new java.util.ArrayList<org.xproce.lab.Video>();
              mutable_bitField0_ |= 0x00000001;
            }
            videos_.add(
                input.readMessage(org.xproce.lab.Video.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        videos_ = java.util.Collections.unmodifiableList(videos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.xproce.lab.Schema.internal_static_org_xproce_lab_VideoStream_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.xproce.lab.Schema.internal_static_org_xproce_lab_VideoStream_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.xproce.lab.VideoStream.class, org.xproce.lab.VideoStream.Builder.class);
  }

  public static final int VIDEOS_FIELD_NUMBER = 1;
  private java.util.List<org.xproce.lab.Video> videos_;
  /**
   * <code>repeated .org.xproce.lab.Video videos = 1;</code>
   */
  public java.util.List<org.xproce.lab.Video> getVideosList() {
    return videos_;
  }
  /**
   * <code>repeated .org.xproce.lab.Video videos = 1;</code>
   */
  public java.util.List<? extends org.xproce.lab.VideoOrBuilder> 
      getVideosOrBuilderList() {
    return videos_;
  }
  /**
   * <code>repeated .org.xproce.lab.Video videos = 1;</code>
   */
  public int getVideosCount() {
    return videos_.size();
  }
  /**
   * <code>repeated .org.xproce.lab.Video videos = 1;</code>
   */
  public org.xproce.lab.Video getVideos(int index) {
    return videos_.get(index);
  }
  /**
   * <code>repeated .org.xproce.lab.Video videos = 1;</code>
   */
  public org.xproce.lab.VideoOrBuilder getVideosOrBuilder(
      int index) {
    return videos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < videos_.size(); i++) {
      output.writeMessage(1, videos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < videos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, videos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.xproce.lab.VideoStream)) {
      return super.equals(obj);
    }
    org.xproce.lab.VideoStream other = (org.xproce.lab.VideoStream) obj;

    if (!getVideosList()
        .equals(other.getVideosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVideosCount() > 0) {
      hash = (37 * hash) + VIDEOS_FIELD_NUMBER;
      hash = (53 * hash) + getVideosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.xproce.lab.VideoStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xproce.lab.VideoStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xproce.lab.VideoStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.xproce.lab.VideoStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.xproce.lab.VideoStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.xproce.lab.VideoStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.xproce.lab.VideoStream prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.xproce.lab.VideoStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.xproce.lab.VideoStream)
      org.xproce.lab.VideoStreamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xproce.lab.Schema.internal_static_org_xproce_lab_VideoStream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xproce.lab.Schema.internal_static_org_xproce_lab_VideoStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xproce.lab.VideoStream.class, org.xproce.lab.VideoStream.Builder.class);
    }

    // Construct using org.xproce.lab.VideoStream.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVideosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (videosBuilder_ == null) {
        videos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        videosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.xproce.lab.Schema.internal_static_org_xproce_lab_VideoStream_descriptor;
    }

    @java.lang.Override
    public org.xproce.lab.VideoStream getDefaultInstanceForType() {
      return org.xproce.lab.VideoStream.getDefaultInstance();
    }

    @java.lang.Override
    public org.xproce.lab.VideoStream build() {
      org.xproce.lab.VideoStream result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.xproce.lab.VideoStream buildPartial() {
      org.xproce.lab.VideoStream result = new org.xproce.lab.VideoStream(this);
      int from_bitField0_ = bitField0_;
      if (videosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          videos_ = java.util.Collections.unmodifiableList(videos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.videos_ = videos_;
      } else {
        result.videos_ = videosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.xproce.lab.VideoStream) {
        return mergeFrom((org.xproce.lab.VideoStream)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.xproce.lab.VideoStream other) {
      if (other == org.xproce.lab.VideoStream.getDefaultInstance()) return this;
      if (videosBuilder_ == null) {
        if (!other.videos_.isEmpty()) {
          if (videos_.isEmpty()) {
            videos_ = other.videos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVideosIsMutable();
            videos_.addAll(other.videos_);
          }
          onChanged();
        }
      } else {
        if (!other.videos_.isEmpty()) {
          if (videosBuilder_.isEmpty()) {
            videosBuilder_.dispose();
            videosBuilder_ = null;
            videos_ = other.videos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            videosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVideosFieldBuilder() : null;
          } else {
            videosBuilder_.addAllMessages(other.videos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.xproce.lab.VideoStream parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.xproce.lab.VideoStream) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.xproce.lab.Video> videos_ =
      java.util.Collections.emptyList();
    private void ensureVideosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        videos_ = new java.util.ArrayList<org.xproce.lab.Video>(videos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.xproce.lab.Video, org.xproce.lab.Video.Builder, org.xproce.lab.VideoOrBuilder> videosBuilder_;

    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public java.util.List<org.xproce.lab.Video> getVideosList() {
      if (videosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(videos_);
      } else {
        return videosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public int getVideosCount() {
      if (videosBuilder_ == null) {
        return videos_.size();
      } else {
        return videosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public org.xproce.lab.Video getVideos(int index) {
      if (videosBuilder_ == null) {
        return videos_.get(index);
      } else {
        return videosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder setVideos(
        int index, org.xproce.lab.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.set(index, value);
        onChanged();
      } else {
        videosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder setVideos(
        int index, org.xproce.lab.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.set(index, builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder addVideos(org.xproce.lab.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.add(value);
        onChanged();
      } else {
        videosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder addVideos(
        int index, org.xproce.lab.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.add(index, value);
        onChanged();
      } else {
        videosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder addVideos(
        org.xproce.lab.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.add(builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder addVideos(
        int index, org.xproce.lab.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.add(index, builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder addAllVideos(
        java.lang.Iterable<? extends org.xproce.lab.Video> values) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, videos_);
        onChanged();
      } else {
        videosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder clearVideos() {
      if (videosBuilder_ == null) {
        videos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        videosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public Builder removeVideos(int index) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.remove(index);
        onChanged();
      } else {
        videosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public org.xproce.lab.Video.Builder getVideosBuilder(
        int index) {
      return getVideosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public org.xproce.lab.VideoOrBuilder getVideosOrBuilder(
        int index) {
      if (videosBuilder_ == null) {
        return videos_.get(index);  } else {
        return videosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public java.util.List<? extends org.xproce.lab.VideoOrBuilder> 
         getVideosOrBuilderList() {
      if (videosBuilder_ != null) {
        return videosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(videos_);
      }
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public org.xproce.lab.Video.Builder addVideosBuilder() {
      return getVideosFieldBuilder().addBuilder(
          org.xproce.lab.Video.getDefaultInstance());
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public org.xproce.lab.Video.Builder addVideosBuilder(
        int index) {
      return getVideosFieldBuilder().addBuilder(
          index, org.xproce.lab.Video.getDefaultInstance());
    }
    /**
     * <code>repeated .org.xproce.lab.Video videos = 1;</code>
     */
    public java.util.List<org.xproce.lab.Video.Builder> 
         getVideosBuilderList() {
      return getVideosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.xproce.lab.Video, org.xproce.lab.Video.Builder, org.xproce.lab.VideoOrBuilder> 
        getVideosFieldBuilder() {
      if (videosBuilder_ == null) {
        videosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.xproce.lab.Video, org.xproce.lab.Video.Builder, org.xproce.lab.VideoOrBuilder>(
                videos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        videos_ = null;
      }
      return videosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.xproce.lab.VideoStream)
  }

  // @@protoc_insertion_point(class_scope:org.xproce.lab.VideoStream)
  private static final org.xproce.lab.VideoStream DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.xproce.lab.VideoStream();
  }

  public static org.xproce.lab.VideoStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoStream>
      PARSER = new com.google.protobuf.AbstractParser<VideoStream>() {
    @java.lang.Override
    public VideoStream parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VideoStream(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VideoStream> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VideoStream> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.xproce.lab.VideoStream getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

